language: python

python:
  - '3.7'

install:
  - pip install -r requirements.txt

script:
  - flake8 drf_recipe/
  - python drf_recipe/manage.py migrate 
  - cd drf_recipe && python manage.py test --failfast --noinput -v 2 --parallel 2
